[project]
name = "pyfem"
version = "0.1.0"
description = "pyFEM: A Python FEM solver"
authors = [
    { name = "Angelo Simone", email = "angelo.simone@unipd.it" }
]


[tool.mypy]
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "scipy.*"
ignore_missing_imports = true
